version: "3.9"

services:
  web:
    build:
      context: .
    container_name: padel-frontend
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start -- --host 0.0.0.0 --port 4200

#Solo para front, puerto 4200